### 1. Manual thresholding

#### 1.1) Let's study the grayscale distribution of the `muscle.bmp` image. What do you notice?

In [1]:
import cv2
import PIL.Image as Image

img_path = "ressources/gray_disc.png"

img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)

print("Image shape:", img.shape)
print("Image size:", img.size / 1024, "KB")
print("Image dtype:", img.dtype)
print("Image Matrix:\n", img, "\n")

cv2.imshow("Gray Disc Image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Image.fromarray(img).show()

Image shape: (800, 800)
Image size: 625.0 KB
Image dtype: uint8
Image Matrix:
 [[210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 ...
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]
 [210 210 210 ... 210 210 210]] 



qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in "/home/hamza_ok/img-processing-labs/.venv/lib/python3.10/site-packages/cv2/qt/plugins"


#### 1.2) Deduce a threshold to separate the two types of cells (black and white) and apply it.

In [2]:
import numpy as np

h1 = np.ones((5, 5), np.float32) / (5 * 5)
h2 = np.ones((11, 11), np.float32) / (11 * 11)
print("Kernel h1:\n", h1, "\nKernel h1 dtype: ", h1.dtype, "\n")
print("Kernel h2:\n", h2, "\nKernel h2 dtype: ", h2.dtype, "\n")

h1_img = cv2.filter2D(src=img, kernel=h1, ddepth=-1)
h2_img = cv2.filter2D(src=img, kernel=h2, ddepth=-1)

cv2.imshow("h1", h1_img)
cv2.imshow("h2", h2_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Kernel h1:
 [[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]] 
Kernel h1 dtype:  float32 

Kernel h2:
 [[0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00

#### 1.3) Segment the image with this visually chosen threshold and visualize the result. What do you notice?

### 2. Gaussian thresholding

#### 2.1) ***Read this:*** If we analyze well the obtained histogram, we can notice that this one is formed by three Gaussians. A large Gaussian on the left, a smaller one in the middle, and a small one on the right. In image processing and analysis, the modeling of the histogram by Gaussian has the objective of representing the distribution of gray levels in terms of Gaussian parameters. This method consists of approximating the histogram of the image by a combination of Gaussian functions for segmentation, object detection, or pattern recognition.

#### 2.2) Write a function that calculates the characteristics of a Gaussian: A (Amplitude), m (mean), sigma (standard deviation). The sigma is defined by:
$$
sigma = \frac{\text{mean} - \text{index\_half\_nv}}{\sqrt{2 \log(2)}}
$$
where `index_half_nv` refers to the gray level whose number of pixels is equal to half the number of maximum pixels in the histogram (see illustration).
![illustration](./ressources%20/illustration_gaussienne.png)

#### 2.3) Determine the characteristics of the Gaussian using the function from the previous question.

#### 2.4) Compute and visualize the Gaussian for the gray levels [0, 255] using the features calculated in the previous question in the following formula:
   $$
   G(nv) = A \exp\left(-\frac{(nv - m)^2}{ 2 \text{sigma} ^2}\right)
   $$
   where `nv` represents the gray level in range [0, 255].

#### 2.5) To which part of the histogram does this Gaussian correspond?

#### 2.6) Extract the second part (`h2`) of the histogram.

#### 2.7) Determine the characteristics of the Gaussian associated with `h2`.

#### 2.8) Compute and visualize the Gaussian for the gray levels [0, 255] using the features calculated in the previous question in the following formula:
   $$
   G2(nv) = A2 \exp\left(-\frac{(nv - m2)^2}{2\text{sigma2}^2}\right)
   $$
   where `nv` represents the gray level interval.


#### 2.9) Display the initial histogram of the image and the two modeled Gaussians \(G1\) and \(G2\) on the same graph. What do you notice?

#### 2.10) By comparing the characteristics of the two Gaussian distributions that fit our histogram, how can we determine an automatic threshold? Write the algorithm allowing you to determine this threshold in sentences.

#### 2.11) Code the algorithm you wrote in the previous question as a function named `Gaussian_thresholding`, which takes as parameter a histogram and returns the optimal threshold based on the parameters of the Gaussians constituting the histogram.

#### 2.12) Threshold the image with the automatically calculated threshold and visualize the result.

### 3. Color Image thresholding

#### 3.1) Load the `2CV.tif` image and check its shape attribute.

#### 3.2) Compute and visualize (side-by-side in the same figure) the histograms of the **R**, **G**, **B** components of the image.

#### 3.3) For your general knowledge: How many colors can such an image store?

#### 3.4) What is the color of the car? On which component could you apply a visually selected threshold to separate the car from its environment?

#### 3.5) Apply a threshold deduced from the histogram of the component you have chosen and view the result (the binary image obtained).

#### 3.6) What do you notice and why?

#### 3.7) Now apply thresholding on the red component and see the result. What do you notice?

#### 3.8) Based on the result of the previous question, what processing could you do to select only the car?

#### 3.9) Try to change the colors of the Chevrolet to red and black and blue and green in the original image. Can the result be improved?